MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  RETINANET_ON: True
  # RetinaNet-VOC doesn't not need P3 for recognizing very small object
  BACKBONE:
      CONV_BODY: "R-50-FPN-RETINANET-VOC"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    ANCHOR_SIZES: (64, 128, 256, 512)
    ANCHOR_STRIDES: (16, 32, 64, 128)
    STRADDLE_THRESH: -1
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
    NUM_CLASSES: 21
DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val", "voc_2012_train", "voc_2012_val")
  TEST: ("voc_2007_test",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (11000,)
  MAX_ITER: 14000
  IMS_PER_BATCH: 16
